/* Seated lab simulation view. Meshes and terminals read the existing live bench;
   camera state is independent of the electrical netlist and worksheet. */
(() => {
  if (typeof document === 'undefined') return;
  const messages={
    '3D lab':'แล็บ 3D','Enter 3D lab':'เข้าสู่แล็บ 3D','Back to 2D':'กลับมุมมอง 2D','Standing at the bench':'มุมมองนั่งทดลอง','Overhead':'มองจากด้านบน','Focus board':'ดูเบรดบอร์ด','Focus scope':'ดูออสซิลโลสโคป','Focus rack':'ดูชุดเครื่องมือ','Full screen':'เต็มหน้าจอ','Exit full screen':'ออกจากเต็มหน้าจอ','Camera help':'วิธีขยับมุมมอง','Close controls':'ปิดแผงควบคุม','LIVE 3D BENCH':'โต๊ะทดลอง 3D · วงจรจริง','WASD to walk · drag to look · scroll to zoom':'ลากเพื่อหมุนมอง · หมุนล้อเพื่อซูม · ลากปุ่มขวาเพื่อเลื่อน','Click a jack, then a breadboard pin to wire. Click an instrument to use its controls.':'คลิกแจ็คแล้วคลิกรูเบรดบอร์ดเพื่อต่อสาย คลิกตัวเครื่องเพื่อเปิดแผงควบคุม','W A S D · walk | Q E · turn | R · home | Esc · return':'W A S D · เลื่อน | Q E · หมุน | R · กลับที่นั่ง | Esc · ปิด','One finger: look. Two fingers: walk and pinch to zoom.':'นิ้วเดียว: หมุนมอง สองนิ้ว: เลื่อนและจีบเพื่อซูม','Walk only in the aisle in front of the bench. Your eye height stays fixed; the table and aisle edges stop movement. Drag to look, use WASD to walk, or right-drag to step. Scrolling zooms your view without moving your body. Instrument and overhead views return to your previous position.':'ลากบนพื้นที่ห้องเพื่อหมุนรอบโต๊ะ กด Shift หรือปุ่มเมาส์ขวาขณะลากเพื่อเลื่อนตำแหน่ง หมุนล้อเมาส์เพื่อเข้าใกล้ การขยับกล้องไม่เปลี่ยนค่าของวงจร','In 3D, click two terminals or drag a jack onto a pin. Zoom in for individual breadboard holes. For exact pin names, open Focus board and use Connections. Double-click a cable to unplug it.':'ในฉาก 3D คลิกขั้วสองจุด หรือลากแจ็คไปยังรูเสียบ ซูมเข้าเพื่อเลือกรูแต่ละรู หากต้องการระบุชื่อรูให้เปิดดูเบรดบอร์ดแล้วใช้ส่วนการต่อสาย ดับเบิลคลิกสายเพื่อถอด','WebGL is unavailable. The 2D bench remains fully functional.':'อุปกรณ์นี้ไม่รองรับ WebGL ยังใช้งานโต๊ะแล็บ 2D ได้ครบ','Graphics paused. Waiting for the browser to restore WebGL.':'พักการแสดงผล กำลังรอเบราว์เซอร์กู้คืน WebGL','Graphics restored.':'กู้คืนการแสดงผลแล้ว','3D camera and circuit workbench':'กล้อง 3D และโต๊ะทดลองวงจร','Camera controls':'การควบคุมกล้อง','Current instrument controls':'แผงควบคุมเครื่องมือที่เลือก','Use the tray to select a component, then click two holes in the 3D breadboard.':'เลือกอุปกรณ์จากถาด แล้วคลิกรูสองจุดบนเบรดบอร์ด 3D','Controls are live; close this panel to return to the full bench.':'แผงนี้ควบคุมเครื่องมือจริงในวงจร ปิดแผงเพื่อกลับไปดูโต๊ะเต็มจอ','Move left':'เลื่อนซ้าย','Move right':'เลื่อนขวา','Move forward':'เลื่อนไปข้างหน้า','Move backward':'เลื่อนถอยหลัง','Zoom in':'ซูมเข้า','Zoom out':'ซูมออก','Saved camera position restored.':'คืนมุมมองกล้องที่บันทึกไว้แล้ว'};
  messages['Standing at the bench']='ยืนหน้าโต๊ะ';
  messages['WASD to walk · drag to look · scroll to zoom']='WASD เดิน · ลากเพื่อมอง · หมุนล้อเพื่อซูม';
  messages['W A S D · walk | Q E · turn | R · home | Esc · return']='W A S D · เดิน | Q E · หัน | R · จุดเริ่มต้น | Esc · กลับ';
  messages['One finger: look. Two fingers: walk and pinch to zoom.']='นิ้วเดียว: หันมอง สองนิ้ว: เดินและจีบเพื่อซูม';
  messages['Walk only in the aisle in front of the bench. Your eye height stays fixed; the table and aisle edges stop movement. Drag to look, use WASD to walk, or right-drag to step. Scrolling zooms your view without moving your body. Instrument and overhead views return to your previous position.']='เดินได้เฉพาะพื้นที่หน้าโต๊ะ ระดับสายตาคงที่ ขอบโต๊ะและขอบทางเดินจะหยุดการเคลื่อนที่ ลากเพื่อหันมอง ใช้ WASD เดิน หรือใช้เมาส์ขวาลากเพื่อก้าว หมุนล้อซูมโดยไม่ย้ายตัว เมื่อปิดเครื่องมือหรือมุมด้านบนจะกลับตำแหน่งเดิม';
  messages['Return to previous view']='กลับมุมมองก่อนหน้า';
  EE.i18n?.addMessages(messages);
  const {V}=EE.SceneMath, el=id=>document.getElementById(id), bench=EE.bench;
  const t=text=>EE.i18n?.t(text)||text;
  const rgb=hex=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255);
  const horizontal=[[1,0,0],[0,0,-1],[0,1,0]], frontCylinder=[[1,0,0],[0,0,1],[0,-1,0]];
  class LabScene {
    constructor(){
      this.active=false;this.lost=false;this.boardOffset=[0,0];this.arranging=false;this.camera={yaw:0,pitch:.31,distance:3.35,target:[0,.99,.04]};this.pointers=new Map();this.keys=new Set();this.dock=null;this.terminals=new Map();this.wirePaths=[];this.renderTimes=[];this.lastSave=0;this.lastTexture=0;this.lastHud=0;this.frames=0;this.fps=0;
      this.navigation='walk';this.player={x:0,z:2.9};this.walkBounds={minX:-1.65,maxX:1.65,minZ:1.08,maxZ:3.4,eyeHeight:1.65};this.inspectReturn=null;
      this.homePose={yaw:0,pitch:.22,distance:innerWidth<700?5.3:3.35,target:[0,.99,.04]};this.camera={...this.homePose,target:[...this.homePose.target]};
      this.root=document.createElement('section');this.root.id='lab-scene';this.root.hidden=true;this.root.setAttribute('aria-label','3D camera and circuit workbench');
      this.root.innerHTML='<canvas id="scene-canvas" tabindex="0" aria-label="3D camera and circuit workbench"></canvas><div class="scene-vignette"></div><div class="scene-top"><div><p>LIVE 3D BENCH</p><h2>FIELDWORK <span>07</span></h2><small id="scene-telemetry"></small></div><div class="scene-actions"><button id="scene-home">Standing at the bench</button><button id="scene-overhead">Overhead</button><button id="scene-fullscreen">Full screen</button><button id="scene-exit">Back to 2D</button></div></div><div class="scene-reticle" aria-hidden="true">+</div><output id="scene-hover" class="scene-hover"></output><div class="scene-dock" id="scene-dock" hidden><div class="scene-dock-heading"><span>Current instrument controls</span><button id="scene-close-dock">Close controls</button></div><p class="scene-dock-note">Controls are live; close this panel to return to the full bench.</p><div id="scene-dock-content"></div></div><div class="scene-bottom"><p id="scene-hint" role="status">Click a jack, then a breadboard pin to wire. Click an instrument to use its controls.</p><div class="scene-focus"><button data-scene-focus="rack">Focus rack</button><button data-scene-focus="board">Focus board</button><button data-scene-focus="scope">Focus scope</button><button id="scene-sheet">Worksheet</button><button id="scene-help">Camera help</button></div><div class="scene-movement" role="group" aria-label="Camera controls"><button data-motion="left" aria-label="Move left">←</button><button data-motion="forward" aria-label="Move forward">↑</button><button data-motion="back" aria-label="Move backward">↓</button><button data-motion="right" aria-label="Move right">→</button><button data-motion="in" aria-label="Zoom in">＋</button><button data-motion="out" aria-label="Zoom out">−</button><span>WASD to walk · drag to look · scroll to zoom</span></div></div>';
      document.body.append(this.root);this.canvas=el('scene-canvas');
      this.toggle=document.createElement('button');this.toggle.id='scene-toggle';this.toggle.textContent='3D lab';this.toggle.setAttribute('aria-pressed','false');document.querySelector('.topbar nav').prepend(this.toggle);
      this.entry=document.createElement('button');this.entry.id='scene-enter';this.entry.className='primary scene-entry';this.entry.textContent='Enter 3D lab';document.querySelector('.lab-heading').append(this.entry);
      const help=document.createElement('dialog');help.id='scene-help-dialog';help.innerHTML='<div class="dialog-header"><span>Camera help</span><button id="scene-help-close">Close ×</button></div><h2>Standing at the bench</h2><p>Walk only in the aisle in front of the bench. Your eye height stays fixed; the table and aisle edges stop movement. Drag to look, use WASD to walk, or right-drag to step. Scrolling zooms your view without moving your body. Instrument and overhead views return to your previous position.</p><p>W A S D · walk | Q E · turn | R · home | Esc · return</p><p>One finger: look. Two fingers: walk and pinch to zoom.</p><p>In 3D, click two terminals or drag a jack onto a pin. Zoom in for individual breadboard holes. For exact pin names, open Focus board and use Connections. Double-click a cable to unplug it.</p>';document.body.append(help);const languageButton=document.createElement('button');languageButton.className='language-toggle';languageButton.dataset.languageToggle='';languageButton.dataset.noI18n='';languageButton.innerHTML='<span data-lang="th">ไทย</span> / <span data-lang="en">EN</span>';languageButton.onclick=()=>EE.i18n.setLanguage(EE.i18n.language==='th'?'en':'th');help.querySelector('.dialog-header').insertBefore(languageButton,el('scene-help-close'));EE.i18n.apply();
      this.toggle.onclick=()=>this.active?this.exit():this.enter();this.entry.onclick=()=>this.enter();el('scene-exit').onclick=()=>this.exit();el('scene-home').onclick=()=>{this.closeDock();this.pose(this.homePose);};el('scene-overhead').onclick=()=>{this.closeDock();this.beginInspection();this.pose({yaw:0,pitch:1.28,distance:2.9,target:[0,.84,.05]});};el('scene-close-dock').onclick=()=>this.closeDock();el('scene-sheet').onclick=()=>el('worksheet-open').click();el('scene-help').onclick=()=>help.showModal();el('scene-help-close').onclick=()=>help.close();
      const back=document.createElement('button');back.id='scene-return-view';back.textContent='Return to previous view';back.hidden=true;back.onclick=()=>this.returnToView();document.querySelector('.scene-actions').prepend(back);
      this.root.addEventListener('keydown',event=>{if(event.key==='Escape'&&this.dock&&!document.querySelector('dialog[open]')){event.preventDefault();event.stopPropagation();this.closeDock();}},true);
      const arrange=document.createElement('button');arrange.id='scene-arrange';arrange.textContent='Arrange board';arrange.onclick=()=>this.setArrange(!this.arranging);document.querySelector('.scene-focus').append(arrange);
      const tabs=document.createElement('div');tabs.className='scene-instrument-tabs';for(const name of ['supply','meter','generator','scope']){const button=document.createElement('button');button.textContent={supply:'Supply',meter:'Meter',generator:'Generator',scope:'Scope'}[name];button.onclick=()=>this.focusInstrument(name);tabs.append(button);}el('scene-dock-content').before(tabs);
      this.root.querySelectorAll('[data-scene-focus]').forEach(b=>b.onclick=()=>this.focus(b.dataset.sceneFocus));
      this.root.querySelectorAll('[data-motion]').forEach(b=>b.onclick=()=>{const action=b.dataset.motion;if(action==='in'||action==='out')this.camera.distance*=action==='in'?.84:1.16;else this.move(action==='left'?-.15:action==='right'?.15:0,action==='forward'?-.15:action==='back'?.15:0);this.clamp();this.save();});
      el('scene-fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{el('scene-fullscreen').disabled=true;}};
      document.addEventListener('fullscreenchange',()=>el('scene-fullscreen').textContent=document.fullscreenElement?'Exit full screen':'Full screen');
      new ResizeObserver(()=>{const height=document.querySelector('.topbar').getBoundingClientRect().height+'px';this.root.style.setProperty('--scene-top',height);document.documentElement.style.setProperty('--nav-height',height);}).observe(document.querySelector('.topbar'));
      this.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.lost=true;this.hint('Graphics paused. Waiting for the browser to restore WebGL.');});
      this.canvas.addEventListener('webglcontextrestored',()=>{try{this.renderer.init();this.renderer.upload(this.boardTexture);this.renderer.upload(this.wallTexture);this.lastTexture=0;this.lost=false;this.hint('Graphics restored.');}catch{this.exit();this.announceUnavailable();}});
      window.addEventListener('languagechange',()=>{this.lastTexture=0;});
      window.addEventListener('blur',()=>this.keys.clear());document.addEventListener('visibilitychange',()=>{this.keys.clear();this.frames=0;this.lastHud=0;});
      window.addEventListener('pagehide',()=>this.save());
      this.bindGestures();try{const board=JSON.parse(localStorage.getItem('ee-lab-board-position')||'null');if(Array.isArray(board)&&board.length===2&&board.every(Number.isFinite)){this.boardOffset=board;this.clampBoard();}}catch{}try{const saved=JSON.parse(localStorage.getItem('ee-lab-walk-view')||'null');if(saved?.version===1&&saved.player&&[saved.player.x,saved.player.z,saved.camera?.yaw,saved.camera?.pitch,saved.camera?.distance].every(Number.isFinite)){this.player=saved.player;this.camera=saved.camera;}}catch{}this.clamp();
      try{if(localStorage.getItem('ee-lab-view')==='3d')this.enter();}catch{}
      requestAnimationFrame(time=>this.frame(time));
    }
    hint(text){el('scene-hint').textContent=text;}
    announceUnavailable(){el('bench-hint').textContent='WebGL is unavailable. The 2D bench remains fully functional.';}
    init(){this.renderer=new EE.WebGLRenderer(this.canvas);this.textures={};for(const name of ['supply','meter','generator','scope']){const c=document.createElement('canvas');c.width=1024;c.height=name==='scope'?720:310;this.textures[name]=c;}
      this.boardTexture=document.createElement('canvas');Object.defineProperties(this.boardTexture,{clientWidth:{value:1000},clientHeight:{value:340}});this.textureBoard=new EE.Breadboard(this.boardTexture);this.textureBoard.guides=false;this.textureBoard.draw([],null);const paper=this.boardTexture.getContext('2d');paper.globalCompositeOperation='destination-over';paper.fillStyle='#d3d2be';paper.fillRect(0,0,this.boardTexture.width,this.boardTexture.height);paper.globalCompositeOperation='source-over';this.renderer.upload(this.boardTexture);
      this.wallTexture=document.createElement('canvas');this.wallTexture.width=1200;this.wallTexture.height=400;const c=this.wallTexture.getContext('2d');c.fillStyle='#e5e6d8';c.fillRect(0,0,1200,400);c.fillStyle='#2b5347';c.font='bold 82px Arial';c.fillText('FIELDWORK',65,125);c.font='32px monospace';c.fillText('ELECTRICAL ENGINEERING  /  07',70,192);c.strokeStyle='#719280';c.lineWidth=4;c.beginPath();for(let i=0;i<1020;i++){const y=285+35*Math.sin(i/52);if(i===0)c.moveTo(i+70,y);else c.lineTo(i+70,y);}c.stroke();this.renderer.upload(this.wallTexture);
      this.instruments=[{name:'generator',panel:'rack',center:[-1.1,.94,-.23],size:[.72,.25,.52]},{name:'meter',panel:'rack',center:[-1.1,1.205,-.23],size:[.72,.25,.52]},{name:'supply',panel:'rack',center:[-1.1,1.5,-.23],size:[.72,.32,.52]},{name:'scope',panel:'scope',center:[1.12,1.095,-.18],size:[.84,.55,.5]}];
      const terminal=(id,p,color)=>this.terminals.set(id,{p,color});
      ['gen.sync','gen.gnd','gen.out'].forEach((id,i)=>terminal(id,[-1.23+i*.21,.86,.06],i===1?'#34413e':'#b7b69d'));
      ['dmm.hi','dmm.lo','dmm.i'].forEach((id,i)=>terminal(id,[-.97+i*.10,1.13,.06],i===1?'#34413e':'#ac5949'));
      ['psu.1+','psu.1-','psu.gnd','psu.2+','psu.2-','psu.3+','psu.3-'].forEach((id,i)=>terminal(id,[-1.39+i*.095,1.398,.06],id.endsWith('+')?'#ad5547':id==='psu.gnd'?'#4d9162':'#34413e'));
      ['scope.ch1','scope.g1','scope.ch2','scope.g2'].forEach((id,i)=>terminal(id,[.85+i*.17,.871,.105],i===0?'#d5bb4c':i===2?'#6faa80':'#34413e'));
      terminal('scope.comp',[.79,.965,.105],'#d5bb4c');terminal('scope.compGround',[.91,.965,.105],'#34413e');
    }
    enter(){if(this.active)return;this.root.hidden=false;try{if(!this.renderer)this.init();}catch{this.root.hidden=true;this.announceUnavailable();return;}this.active=true;bench.scope.fallbackSize={width:460,height:300};document.querySelectorAll('#workbench,.lab-heading,.experiment-bar,.bench-footer,.mobile-tabs').forEach(node=>node.inert=true);document.body.classList.add('scene-mode');this.toggle.setAttribute('aria-pressed','true');this.canvas.focus({preventScroll:true});this.lastTexture=0;this.lastTime=0;EE.missions?.mount();try{localStorage.setItem('ee-lab-view','3d');}catch{} }
    exit(){EE.interaction?.closeBoard();this.setArrange(false);this.closeDock();this.returnToView();this.save();this.active=false;bench.scope.fallbackSize=null;document.querySelectorAll('#workbench,.lab-heading,.experiment-bar,.bench-footer,.mobile-tabs').forEach(node=>node.inert=false);this.root.hidden=true;this.keys.clear();this.pointers.clear();this.drag=null;document.body.classList.remove('scene-mode');this.toggle.setAttribute('aria-pressed','false');try{localStorage.setItem('ee-lab-view','2d');}catch{}EE.missions?.mount();bench.redraw();this.toggle.focus({preventScroll:true});}
    snapshotView(){return {camera:{...this.camera,target:[...this.camera.target]},player:{...this.player},navigation:this.navigation};}
    restoreView(view){if(!view)return;this.cameraTween=null;this.camera={...view.camera,target:[...view.camera.target]};this.player={...view.player};this.navigation=view.navigation;this.keys.clear();this.clamp();this.save();}
    beginInspection(){if(!this.inspectReturn)this.inspectReturn=this.snapshotView();this.navigation='inspect';el('scene-return-view').hidden=false;}
    returnToView(){if(this.dock){this.closeDock();return;}if(this.inspectReturn){const previous=this.inspectReturn;this.inspectReturn=null;this.arranging=false;this.root.classList.remove('scene-arranging');el('scene-arrange').setAttribute('aria-pressed','false');this.restoreView(previous);}el('scene-return-view').hidden=true;}
    save(){try{const view=this.dock?.returnView||this.inspectReturn||this.snapshotView();if(view.navigation==='walk')localStorage.setItem('ee-lab-walk-view',JSON.stringify({version:1,...view}));localStorage.setItem('ee-lab-board-position',JSON.stringify(this.boardOffset));}catch{}}
    clamp(){
      const c=this.camera;c.yaw=Math.max(-1.25,Math.min(1.25,c.yaw));c.pitch=Math.max(.10,Math.min(this.navigation==='walk'?1.05:1.4,c.pitch));c.distance=Math.max(.65,Math.min(5.3,c.distance));
      if(this.navigation==='walk'){
        const bounds=this.walkBounds;this.player.x=Math.max(bounds.minX,Math.min(bounds.maxX,this.player.x));this.player.z=Math.max(bounds.minZ,Math.min(bounds.maxZ,this.player.z));
        // Keep the eye on a standing character. Looking rotates the head, not the body around the table.
        c.target=[this.player.x-Math.sin(c.yaw)*Math.cos(c.pitch)*c.distance,bounds.eyeHeight-Math.sin(c.pitch)*c.distance,this.player.z-Math.cos(c.yaw)*Math.cos(c.pitch)*c.distance];
        c.fov=2*Math.atan(Math.tan(Math.PI/6)*c.distance/3.35);
      }else{c.fov=Math.PI/3;c.target=c.target.map((v,i)=>Math.max([-1.4,.76,-.6][i],Math.min([1.4,1.6,.85][i],v)));}
    }
    pose(pose){this.cameraTween=null;this.hover=null;el('scene-hover').textContent='';if(pose===this.homePose){this.closeDock(false);this.inspectReturn=null;this.navigation='walk';this.player={x:0,z:2.9};this.arranging=false;this.root.classList.remove('scene-arranging');el('scene-arrange').setAttribute('aria-pressed','false');el('scene-return-view').hidden=true;}else this.navigation='inspect';this.camera={...pose,target:[...pose.target]};this.clamp();this.save();this.canvas.focus({preventScroll:true});}
    flyTo(pose){if(matchMedia('(prefers-reduced-motion: reduce)').matches){this.pose(pose);return;}this.cameraTween={from:{...this.camera,target:[...this.camera.target]},to:pose,elapsed:0};this.hover=null;el('scene-hover').textContent='';this.canvas.focus({preventScroll:true});}
    move(x,z){if(!x&&!z)return;const a=this.camera.yaw;if(this.navigation==='walk'){this.player.x+=x*Math.cos(a)+z*Math.sin(a);this.player.z+=-x*Math.sin(a)+z*Math.cos(a);}else{this.camera.target[0]+=x*Math.cos(a)+z*Math.sin(a);this.camera.target[2]+=-x*Math.sin(a)+z*Math.cos(a);}this.clamp();}
    focus(panel){if(panel==='board'&&EE.interaction){EE.interaction.openBoard();return;}this.focusInstrument(panel==='rack'?'generator':'scope');}
    focusInstrument(name){
      if(!['supply','meter','generator','scope'].includes(name))return;
      EE.interaction?.closeBoard();const previous=this.dock?.returnView;this.closeDock(false);this.setArrange(false);const returnView=previous||this.snapshotView();this.navigation='inspect';
      const instrument=this.instruments.find(item=>item.name===name);
      const target=[...instrument.center];target[0]+=innerWidth>900?.26:0;
      this.flyTo({yaw:name==='scope'?-.05:.06,pitch:.18,distance:name==='scope'?1.6:1.35,target});
      const source=name==='scope'?document.querySelector('.instrument.scope'):el(name);
      this.dock={source,marker:document.createComment('scene-controls-home'),name,returnView};source.before(this.dock.marker);el('scene-dock-content').append(source);el('scene-dock').hidden=false;source.inert=false;this.keys.clear();this.hint('Controls are live; close this panel to return to the full bench.');bench.redraw();
    }
    setArrange(value){if(!value&&this.arranging){this.returnToView();return;}this.arranging=value;this.root.classList.toggle('scene-arranging',value);el('scene-arrange').setAttribute('aria-pressed',String(value));if(value){this.closeDock();this.beginInspection();this.pose({yaw:0,pitch:1.05,distance:3.1,target:[0,.84,.10]});this.hint('Drag the board on the tabletop. Press Esc when finished.');}else this.hint('Click a jack, then a breadboard pin to wire. Click an instrument to use its controls.');}
    clampBoard(){this.boardOffset[0]=Math.max(-1.1,Math.min(1.1,this.boardOffset[0]));this.boardOffset[1]=Math.max(-.65,Math.min(.22,this.boardOffset[1]));if(Math.abs(this.boardOffset[0])>.05)this.boardOffset[1]=Math.max(-.025,this.boardOffset[1]);}
    tablePoint(x,y){const ray=this.renderer.ray(x,y),d=(.858-ray.origin[1])/ray.direction[1];return d>0?V.add(ray.origin,V.scale(ray.direction,d)):null;}
    closeDock(restore=true){if(!this.dock)return;const previous=this.dock.returnView;this.dock.marker.replaceWith(this.dock.source);this.dock=null;el('scene-dock').hidden=true;if(restore){this.restoreView(previous);this.hint('Click a jack, then a breadboard pin to wire. Click an instrument to use its controls.');}bench.redraw();this.canvas.focus({preventScroll:true});}
    pinPosition(id){const p=bench.board.byId.get(id);return p?[-.65+p.x/1000*1.3+this.boardOffset[0],.858,.10+(p.y+15)/340*.46+this.boardOffset[1]]:null;}
    terminalPosition(id){return this.terminals.get(id)?.p||this.pinPosition(id);}
    endpoint(id){const p=this.terminalPosition(id);return p&&this.renderer?.viewProjection?this.renderer.project(p):null;}
    boardPoint(x,y){const p=this.tablePoint(x,y);if(!p)return null;const px=p[0]-this.boardOffset[0],pz=p[2]-this.boardOffset[1];return px>=-.65&&px<=.65&&pz>=.10&&pz<=.56?p:null;}
    pinAt(x,y){const point=this.boardPoint(x,y);if(!point)return null;const px=(point[0]-this.boardOffset[0]+.65)/1.3*1000,py=(point[2]-this.boardOffset[1]-.10)/.46*340-15;let pin=null,dist=12;for(const p of bench.board.pins){const d=Math.hypot(p.x-px,p.y-py);if(d<dist){dist=d;pin=p;}}return pin?.id || null;}
    pick(x,y){
      if(this.arranging&&this.boardPoint(x,y))return{board:true};
      for(const [id,terminal] of this.terminals){const p=this.renderer.project(terminal.p);if(p.visible&&Math.hypot(p.x-x,p.y-y)<5)return{terminal:id};}
      if(!bench.interaction().pending&&!bench.interaction().placing){
        for(const instrument of this.instruments){const p=instrument.center,s=instrument.size;
          const power=this.renderer.project([p[0]-s[0]*.4,p[1]+s[1]*(instrument.name==='supply'?.28:-.31),p[2]+s[2]/2+.026]);
          if(['generator','supply'].includes(instrument.name)&&Math.hypot(power.x-x,power.y-y)<12)return{power:instrument.name};
          const knob=this.renderer.project([p[0]+s[0]*.36,p[1]+(instrument.name==='scope'?-.1:.018),p[2]+s[2]/2+.04]);
          if(instrument.name!=='meter'&&Math.hypot(knob.x-x,knob.y-y)<18)return{knob:instrument.name};
        }
        for(const part of [...bench.model.parts].reverse()){const a=this.pinPosition(part.a),b=this.pinPosition(part.b);if(!a||!b)continue;const p=this.renderer.project([(a[0]+b[0])/2,.89,(a[2]+b[2])/2]);if(Math.hypot(p.x-x,p.y-y)<14)return{part:part.id};}
      }
      let found=null,nearest=13;for(const [id,terminal] of this.terminals){const p=this.renderer.project(terminal.p),distance=Math.hypot(p.x-x,p.y-y);if(p.visible&&distance<nearest){nearest=distance;found=id;}}if(found)return{terminal:found};
      const point=this.boardPoint(x,y);if(point){const pin=this.pinAt(x,y);return pin?{terminal:pin}:{panel:'board'};}
      const ray=this.renderer.ray(x,y);let near=Infinity,hit=null;for(const instrument of this.instruments){const z=instrument.center[2]+instrument.size[2]/2+.004,d=(z-ray.origin[2])/ray.direction[2];if(d<0||d>near)continue;const p=V.add(ray.origin,V.scale(ray.direction,d));if(Math.abs(p[0]-instrument.center[0])<instrument.size[0]/2&&Math.abs(p[1]-instrument.center[1])<instrument.size[1]/2){near=d;hit=instrument;}}return hit?{panel:hit.panel,instrument:hit.name}:{};
    }
    stepKnob(name,direction){if(name==='generator'){bench.model.generator.turn(direction);bench.update();}else if(name==='supply'){const c=bench.model.psu.channels[0];c.setVoltage=Math.max(0,Math.min(32,c.setVoltage+direction*.1));bench.update();}else{bench.scope.step('time',direction);bench.refreshReadings();}bench.audio.play('detent');}
    wireAt(x,y){let best=null,distance=9;for(const wire of this.wirePaths)for(let i=1;i<wire.points.length;i++){const a=this.renderer.project(wire.points[i-1]),b=this.renderer.project(wire.points[i]),dx=b.x-a.x,dy=b.y-a.y;const u=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/(dx*dx+dy*dy||1)));const d=Math.hypot(x-a.x-u*dx,y-a.y-u*dy);if(d<distance){distance=d;best=wire.id;}}return best;}
    bindGestures(){const c=this.canvas;
      c.addEventListener('contextmenu',e=>e.preventDefault());
      c.addEventListener('pointerdown',e=>{if(!this.active||this.lost)return;e.preventDefault();this.cameraTween=null;c.focus({preventScroll:true});c.setPointerCapture(e.pointerId);this.keys.clear();const hit=this.pick(e.clientX,e.clientY);this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});this.drag={x:e.clientX,y:e.clientY,moved:false,hit,pan:e.button===2||e.shiftKey,offset:[...this.boardOffset],table:this.tablePoint(e.clientX,e.clientY),knobY:e.clientY};if(hit.board||hit.knob)EE.history.begin(hit.board?'Move breadboard':undefined);if(hit.part)EE.interaction.select(hit.part);if(this.pointers.size===2){const[a,b]=[...this.pointers.values()];this.pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),x:(a.x+b.x)/2,y:(a.y+b.y)/2};this.drag.moved=true;}});
      c.addEventListener('pointermove',e=>{if(!this.active||this.lost)return;const p=this.pointers.get(e.pointerId);if(!p){const hit=this.pick(e.clientX,e.clientY);this.hover=hit.terminal||null;this.hoverInstrument=hit.instrument||hit.knob||hit.power;el('scene-hover').textContent=this.hover||hit.part||(hit.knob?t('Rotate')+' · '+hit.knob:hit.power?'OUTPUT':hit.board?t('Move breadboard'):hit.instrument?t({supply:'Supply',meter:'Meter',generator:'Generator',scope:'Scope'}[hit.instrument]):'');c.style.cursor=hit.board?'move':hit.part||hit.knob?'grab':this.hover?'crosshair':hit.panel||hit.power?'pointer':'grab';return;}
        const dx=e.clientX-p.x,dy=e.clientY-p.y;p.x=e.clientX;p.y=e.clientY;
        if(this.pointers.size>=2&&this.pinch){const[a,b]=[...this.pointers.values()],distance=Math.hypot(a.x-b.x,a.y-b.y),x=(a.x+b.x)/2,y=(a.y+b.y)/2;this.camera.distance*=this.pinch.distance/Math.max(distance,10);this.move(-(x-this.pinch.x)*.002,.002*(y-this.pinch.y));this.pinch={distance,x,y};this.drag.moved=true;}
        else if(this.drag){const d=this.drag;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>5)d.moved=true;if(d.moved){if(d.hit.board&&!d.pan){const point=this.tablePoint(e.clientX,e.clientY);if(point&&d.table){this.boardOffset=[d.offset[0]+point[0]-d.table[0],d.offset[1]+point[2]-d.table[2]];this.clampBoard();}}
          else if(d.hit.part&&!d.pan){const part=bench.model.parts.find(p=>p.id===d.hit.part);this.partPreview=EE.interaction.candidate(part,this.pinAt(e.clientX,e.clientY));}
          else if(d.hit.knob&&!d.pan){if(Math.abs(e.clientY-d.knobY)>8){this.stepKnob(d.hit.knob,e.clientY<d.knobY?1:-1);d.knobY=e.clientY;}}
          else if(d.hit.terminal&&!d.pan){this.preview={a:d.hit.terminal,p:this.boardPoint(e.clientX,e.clientY)||this.terminalPosition(this.pick(e.clientX,e.clientY).terminal)};}
          else if(d.pan)this.move(-dx*this.camera.distance*.0015,dy*this.camera.distance*.0015);else{this.camera.yaw-=dx*.005;this.camera.pitch+=dy*.004;}}}this.clamp();});
      const end=e=>{const drag=this.drag,hadPinch=!!this.pinch;this.pointers.delete(e.pointerId);if(this.pointers.size===0){if(e.type==='pointerup'&&drag&&!hadPinch){const hit=this.pick(e.clientX,e.clientY),start=drag.hit;if(drag.moved&&start.part&&!drag.pan){EE.interaction.commit(this.partPreview);}else if(drag.moved&&start.terminal&&hit.terminal&&start.terminal!==hit.terminal&&!drag.pan){bench.cancelInteraction();bench.selectTerminal(start.terminal);bench.selectTerminal(hit.terminal);EE.interaction.pulse(hit.terminal);}else if(!drag.moved&&!drag.pan){if(hit.power){if(hit.power==='generator')bench.model.generator.enabled=!bench.model.generator.enabled;else bench.model.psu.channels[0].enabled=!bench.model.psu.channels[0].enabled;bench.update();bench.audio.play('relay');}else if(hit.knob)this.stepKnob(hit.knob,1);else if(hit.part)EE.interaction.select(hit.part);else if(hit.terminal)bench.selectTerminal(hit.terminal);else if(hit.panel&&!this.wireAt(e.clientX,e.clientY)){if(hit.instrument)this.focusInstrument(hit.instrument);else this.focus(hit.panel);}}}else if(drag?.hit.board)this.boardOffset=drag.offset;
          this.drag=null;this.pinch=null;this.preview=null;this.partPreview=null;EE.history.end();this.save();}else if(this.drag)this.drag.moved=true;};
      c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end);
      c.addEventListener('wheel',e=>{e.preventDefault();this.cameraTween=null;const hit=this.pick(e.clientX,e.clientY);if(hit.knob){EE.history.begin();this.stepKnob(hit.knob,e.deltaY<0?1:-1);clearTimeout(this.knobTimer);this.knobTimer=setTimeout(()=>EE.history.end(),200);}else{this.camera.distance*=Math.exp(Math.max(-200,Math.min(200,e.deltaY))*.0015);this.clamp();this.save();}},{passive:false});
      c.addEventListener('dblclick',e=>{const best=this.wireAt(e.clientX,e.clientY);if(best){bench.model.wires=bench.model.wires.filter(w=>w.id!==best);bench.update();}});
      c.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey)return;const key=e.key.toLowerCase();if(['w','a','s','d','q','e','arrowup','arrowdown','arrowleft','arrowright'].includes(key)){e.preventDefault();this.keys.add(key);}if(key==='r'){e.preventDefault();this.pose(this.homePose);}if(key==='escape'){e.preventDefault();if(this.dock)this.closeDock();else if(this.inspectReturn)this.returnToView();else this.exit();}});c.addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase()));c.addEventListener('blur',()=>this.keys.clear());
    }
    drawTextures(){for(const instrument of this.instruments){const name=instrument.name,canvas=this.textures[name],ctx=canvas.getContext('2d'),model=bench.model;ctx.fillStyle='#c5caba';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#4b5948';ctx.font='bold 32px Arial';ctx.fillText(name==='supply'?'SIGLENT  SPD3303C':name==='scope'?'KEYSIGHT  InfiniiVision':name==='meter'?'hp   34401A  MULTIMETER':'hp   33120A  FUNCTION GENERATOR',30,45);ctx.fillStyle='#15262b';ctx.fillRect(30,65,name==='scope'?960:770,name==='scope'?530:150);
        if(name==='scope')this.drawScopeTexture(ctx);
        else if(name==='supply'){ctx.font='44px monospace';model.psu.channels.slice(0,2).forEach((ch,i)=>{ctx.fillStyle='#e0a070';ctx.fillText(ch.voltage.toFixed(2)+' V',55+i*390,135);ctx.fillText(ch.current.toFixed(3)+' A',55+i*390,192);ctx.font='21px monospace';ctx.fillStyle=ch.mode==='CC'?'#f29379':'#91c999';ctx.fillText('CH'+(i+1)+' '+ch.mode,230+i*390,91);ctx.font='44px monospace';});}
        else{ctx.fillStyle='#a9ddc1';ctx.font='54px monospace';const display=model.generator.display(),reading=name==='meter'?el('dmm-reading').textContent:display.text+' '+display.unit;ctx.fillText(reading,55,145,715);ctx.font='23px monospace';ctx.fillStyle='#729e87';ctx.fillText(name==='meter'?model.dmm.mode:model.generator.waveform.toUpperCase()+'  '+model.generator.vpp.toFixed(2)+' Vpp  '+(model.generator.load==='Hi-Z'?'HIGH Z':'50 OHM'),55,194,715);}
        if(name!=='scope'){ctx.fillStyle='#4d614e';ctx.font='19px monospace';ctx.fillText(name==='supply'?'CH1      GND      CH2          CH3':name==='meter'?'DC V    AC V    Ω    FREQ                 HI   LO    3A':'SINE    SQUARE    TRIANGLE        SYNC    GND    OUT',40,260);}
        this.renderer.upload(canvas);}}
    drawScopeTexture(ctx){
      const s=bench.scope;ctx.fillStyle='#d8ded9';ctx.fillRect(715,65,285,550);
      ctx.fillStyle='#0b1519';ctx.fillRect(30,65,670,530);
      if(s.canvas.width&&s.canvas.height)ctx.drawImage(s.canvas,45,100,500,405);
      ctx.font='17px monospace';ctx.fillStyle='#dce8df';ctx.fillText(s.acquisition+'  '+s.status+'  '+EE.formatTime(s.timeDiv)+'/DIV',45,87,630);
      s.measurements.forEach((m,i)=>{ctx.fillStyle=m.source===0?'#f4d85a':'#87d69c';ctx.fillText(m.type+'('+(m.source+1)+')',550,140+i*80,140);ctx.fillText(s.measurementValue(m.type,m.source),550,165+i*80,140);});
      s.softkeys().forEach(([name,value],i)=>{const x=38+i*110;ctx.fillStyle='#334b3b';ctx.fillRect(x,514,105,65);ctx.fillStyle='#e1ecdb';ctx.font='15px Arial';ctx.fillText(name,x+4,537,97);ctx.fillText(value,x+4,562,97);ctx.fillStyle='#e1e7de';ctx.fillRect(x+20,599,65,18);});
      const key=(x,y,w,label,color='#f0f2e9')=>{ctx.fillStyle=color;ctx.fillRect(x,y,w,29);ctx.fillStyle='#34433a';ctx.font='16px Arial';ctx.fillText(label,x+5,y+20,w-10);};
      const dial=(x,y,label,color='#c5cdbf')=>{ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,24,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#758772';ctx.lineWidth=2;ctx.stroke();ctx.beginPath();ctx.moveTo(x,y-18);ctx.lineTo(x,y-8);ctx.stroke();ctx.fillStyle='#40523f';ctx.font='15px Arial';ctx.fillText(label,x-39,y+42,90);};
      dial(752,100,'Entry');key(798,78,98,'Run/Stop',s.run?'#a2dcb0':'#e3a19b');key(902,78,89,'Single');key(798,119,98,'Default');key(902,119,89,'Auto Scale');
      dial(789,195,'TIME/DIV');dial(924,195,'Position');key(730,260,78,'Meas');key(817,260,78,'Cursors');key(904,260,85,'Acquire');
      dial(751,336,'Level');key(802,309,106,'Trigger');key(915,309,70,'Slope');
      dial(777,470,'CH1 V/DIV');dial(925,470,'CH2 V/DIV');key(757,523,38,'1','#f4d85a');key(905,523,38,'2','#87d69c');
      ctx.fillStyle='#3b513e';ctx.font='18px Arial';ctx.fillText('PROBE COMP    1 kHz / 3 Vp-p',45,644);ctx.fillText('CH1                          CH2',300,681);
    }
    drawRoom(){const r=this.renderer,box=(p,s,c)=>r.draw('box',p,s,c);box([0,-.06,0],[9,.10,9],[.26,.32,.32]);for(let i=-4;i<=4;i++){box([i,0,0],[.012,.002,8],[.32,.39,.38]);box([0,0,i],[8,.002,.012],[.32,.39,.38]);}box([0,1.65,-1.6],[7,3.3,.09],[.60,.66,.63]);box([-3.2,1.65,.2],[.09,3.3,3.6],[.40,.50,.48]);box([0,.08,-1.53],[7,.16,.08],[.26,.35,.32]);r.draw('plane',[0,2.22,-1.545],[1.8,.6,1],[1,1,1],this.wallTexture,undefined,true);
      box([0,.765,0],[3.65,.10,1.62],[.59,.45,.30]);box([0,.82,0],[3.62,.012,1.60],[.74,.64,.46]);box([0,.735,.805],[3.65,.06,.035],[.35,.27,.20]);for(const x of [-1.6,1.6])for(const z of [-.58,.58]){box([x,.365,z],[.065,.73,.065],[.19,.25,.25]);box([x,.06,z],[.12,.06,.12],[.11,.15,.15]);}box([0,.23,-.57],[3.2,.045,.045],[.21,.28,.27]);box([0,.829,.24],[1.85,.009,1.10],[.15,.31,.26]);box([0,.841,-.59],[3.5,.04,.12],[.27,.31,.26]);
      // Rear outlet strip and task light: modeled geometry, no downloaded assets.
      box([-1.65,1.10,-.55],[.032,.54,.032],[.25,.30,.26]);r.segment([-1.65,1.36,-.55],[-.85,1.83,-.36],.018,[.42,.48,.39]);box([-.80,1.83,-.36],[.4,.04,.12],[.20,.27,.24]);box([-.80,1.808,-.36],[.32,.01,.08],[1,.94,.68]);
      for(const x of [-.6,-.25,.1,.45]){box([x,1.02,-1.53],[.14,.18,.025],[.8,.82,.72]);for(const dx of [-.026,.026])box([x+dx,1.04,-1.512],[.016,.032,.008],[.28,.34,.30]);}
      box([.09,.842,.66],[.72,.012,.22],[.87,.85,.71]);box([.09,.85,.63],[.60,.002,.008],[.52,.64,.52]);box([.09,.85,.67],[.60,.002,.003],[.64,.71,.6]);
    }
    drawInstruments(){const r=this.renderer;for(const instrument of this.instruments){const {center:p,size:s,name}=instrument;r.draw('box',p,s,this.hoverInstrument===name?[.72,.75,.62]:[.62,.67,.58]);if(['generator','supply'].includes(name))r.draw('box',[p[0]-s[0]*.4,p[1]+s[1]*(instrument.name==='supply'?.28:-.31),p[2]+s[2]/2+.013],[.045,.025,.019],(name==='generator'?bench.model.generator.enabled:bench.model.psu.channels[0].enabled)?[.47,.78,.5]:[.23,.31,.25]);r.draw('plane',[p[0],p[1],p[2]+s[2]/2+.002],[s[0]*.965,s[1]*.94,1],[1,1,1],this.textures[name],undefined,true);for(const x of [-1,1])r.draw('box',[p[0]+x*s[0]*.40,p[1]-s[1]/2-.009,p[2]],[.07,.018,.32],[.15,.22,.19]);for(let i=0;i<7;i++)r.draw('box',[p[0]+s[0]/2+.001,p[1]+s[1]*.25-i*.018,p[2]],[.002,.006,.22],[.33,.39,.33]);if(name!=='meter'){const x=p[0]+s[0]*.36,y=p[1]+(name==='scope'?-.1:.018),z=p[2]+s[2]/2+.017;r.draw('cylinder',[x,y,z],[.035,.027,.035],[.72,.76,.66],null,frontCylinder);const angle=(name==='generator'?Math.log10(bench.model.generator.frequency)*240:name==='supply'?bench.model.psu.channels[0].setVoltage*12:(bench.scope.timeIndex-3)*35)*Math.PI/180;r.segment([x+Math.sin(angle)*.012,y+Math.cos(angle)*.012,z+.016],[x+Math.sin(angle)*.027,y+Math.cos(angle)*.027,z+.016],.002,[.3,.4,.3]);}}
      const selected=bench.interaction().pending;for(const[id,{p,color}]of this.terminals){r.draw('cylinder',p,[.018,.025,.018],id===this.hover||id===selected||id===EE.ux?.terminal?[.95,.81,.4]:rgb(color),null,frontCylinder);r.draw('cylinder',[p[0],p[1],p[2]+.014],[.008,.003,.008],[.07,.13,.12],null,frontCylinder);}}
    drawBoard(){const r=this.renderer;r.draw('box',[this.boardOffset[0],.842,.33+this.boardOffset[1]],[1.31,.024,.465],[.64,.66,.56]);r.draw('plane',[this.boardOffset[0],.856,.33+this.boardOffset[1]],[1.3,.46,1],[1,1,1],this.boardTexture,horizontal,true);
      for(const original of bench.model.parts){const part=this.partPreview?.valid&&this.partPreview.id===original.id?this.partPreview:original;const a=this.pinPosition(part.a),b=this.pinPosition(part.b);if(!a||!b)continue;a[1]=b[1]=.864;const center=V.scale(V.add(a,b),.5);center[1]+=.024;r.segment(a,center,.0028,[.65,.66,.55]);r.segment(center,b,.0028,[.65,.66,.55]);if(part.type==='R'){const axis=V.norm(V.sub(b,a)),half=V.scale(axis,.047);r.segment(V.sub(center,half),V.add(center,half),.014,part.state==='burnt'?[.10,.09,.08]:[.68,.54,.32]);if(part.state!=='burnt')for(const[u,color]of [[-.030,[.34,.17,.08]],[-.013,[.05,.05,.045]],[.006,[.61,.16,.10]],[.032,[.76,.59,.22]]]){const mid=V.add(center,V.scale(axis,u));r.segment(V.add(mid,V.scale(axis,-.003)),V.add(mid,V.scale(axis,.003)),.0145,color);}}else if(part.value<.5e-6)r.draw('cylinder',center,[.017,.02,.017],[.69,.40,.18]);else{center[1]+=.025;r.draw('cylinder',center,[.024,.075,.024],[.13,.25,.28]);r.draw('cylinder',[center[0],center[1]+.039,center[2]],[.022,.005,.022],part.state==='ruptured'?[.11,.13,.11]:[.62,.67,.63]);const towardNegative=V.norm(V.sub(b,a));r.draw('box',V.add(center,V.scale(towardNegative,.022)),[.01,.06,.01],[.73,.77,.65]);if(part.state==='ruptured'){r.segment([center[0]-.018,center[1]+.045,center[2]-.018],[center[0]+.018,center[1]+.052,center[2]+.018],.003,[.11,.1,.07]);}}}
      for(const id of [this.hover,bench.interaction().pending,bench.interaction().placing?.a,...(EE.missions?.targets()||[]),...(bench.model.parts.filter(p=>p.id===EE.interaction?.selected).flatMap(p=>[p.a,p.b]))]){const p=this.pinPosition(id);if(p)r.draw('cylinder',[p[0],.865,p[2]],[.008,.005,.008],[.96,.76,.30]);}}
    cablePoints(a,b){const points=[];const distance=Math.hypot(...V.sub(a,b));for(let i=0;i<=20;i++){const u=i/20,p=a.map((v,k)=>v+(b[k]-v)*u);p[1]=Math.max(.868,p[1]-Math.sin(Math.PI*u)*Math.min(.3,distance*.26));p[2]+=Math.sin(Math.PI*u)*.10;points.push(p);}return points;}
    drawWires(){this.wirePaths=[];for(const wire of bench.model.wires){const a=this.terminalPosition(wire.a),b=this.terminalPosition(wire.b);if(!a||!b)continue;const points=this.cablePoints(a,b);this.wirePaths.push({id:wire.id,points});for(let i=1;i<points.length;i++)this.renderer.segment(points[i-1],points[i],.004,rgb(wire.color));}if(this.preview?.p){const a=this.terminalPosition(this.preview.a);if(a){const points=this.cablePoints(a,this.preview.p);for(let i=1;i<points.length;i++)this.renderer.segment(points[i-1],points[i],.003,[.96,.80,.35]);}}}
    tick(dt){
      if(this.cameraTween){const animation=this.cameraTween;animation.elapsed+=dt;const u=Math.min(1,animation.elapsed/.32),ease=u*u*(3-2*u);for(const key of ['yaw','pitch','distance'])this.camera[key]=animation.from[key]+(animation.to[key]-animation.from[key])*ease;this.camera.target=animation.from.target.map((value,i)=>value+(animation.to.target[i]-value)*ease);if(u===1)this.cameraTween=null;}
      if(this.keys.size)this.cameraTween=null;
      if(!document.querySelector('dialog[open]')){const k=this.keys,x=(k.has('d')||k.has('arrowright')?1:0)-(k.has('a')||k.has('arrowleft')?1:0),z=(k.has('s')||k.has('arrowdown')?1:0)-(k.has('w')||k.has('arrowup')?1:0);
        if(x||z){if(this.navigation!=='walk'){this.closeDock();this.returnToView();if(this.navigation!=='walk')this.pose(this.homePose);}const speed=Math.min(dt,.05)*.85/Math.max(1,Math.hypot(x,z));this.move(x*speed,z*speed);}
        this.camera.yaw+=((k.has('e')?1:0)-(k.has('q')?1:0))*Math.min(dt,.05)*.6;this.clamp();}else this.keys.clear();
    }
    frame(time){requestAnimationFrame(t=>this.frame(t));if(!this.active||this.lost||document.hidden||EE.interaction?.open)return;const dt=Math.min(.04,(time-(this.lastTime||time))/1000);this.lastTime=time;
      if(!EE.interaction?.open)this.tick(dt);
      const begin=performance.now();this.renderer.begin(this.camera);if(time-this.lastTexture>66||!this.lastTexture){this.drawTextures();this.lastTexture=time;}this.drawRoom();this.drawInstruments();this.drawBoard();this.drawWires();this.renderMs=performance.now()-begin;this.frames++;
      if(time-this.lastHud>1000){this.fps=this.lastHud?Math.round(this.frames*1000/(time-this.lastHud)):0;this.frames=0;this.lastHud=time;el('scene-telemetry').textContent=bench.model.generator.frequency.toFixed(1)+' Hz  /  '+(bench.model.signals[1].vpp).toFixed(2)+' Vpp  /  '+this.fps+' FPS';const hint=el('bench-hint').textContent;if(bench.interaction().pending||bench.interaction().placing||bench.model.failure.active.size)el('scene-hint').textContent=hint;}
      if(time-this.lastSave>3000){this.save();this.lastSave=time;}
    }
  }
  EE.LabScene=LabScene;EE.scene=new LabScene();if(EE.history&&!EE.history.past.length)EE.history.current=EE.history.snapshot();
})();
