worker_processes 1;
pid /Users/3rapat/student/internship/CODEFIN/project/cwms/vahalla-wealth/private-docs/other-project/uni-work/engineering-problem/electrical-engineering-lab/part1/lab7/nginx.pid;
error_log /Users/3rapat/student/internship/CODEFIN/project/cwms/vahalla-wealth/private-docs/other-project/uni-work/engineering-problem/electrical-engineering-lab/part1/lab7/error.log;

events {
    worker_connections 1024;
}

http {
    include /opt/homebrew/etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    access_log /Users/3rapat/student/internship/CODEFIN/project/cwms/vahalla-wealth/private-docs/other-project/uni-work/engineering-problem/electrical-engineering-lab/part1/lab7/access.log;

    server {
        listen 8080;
        server_name localhost;
        root /Users/3rapat/student/internship/CODEFIN/project/cwms/vahalla-wealth/private-docs/other-project/uni-work/engineering-problem/electrical-engineering-lab/part1/lab7;
        index index.html;
    }
}
