const assert=require('node:assert/strict');
require('./physics.test.cjs');
let count=0;
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
const test=(name,fn)=>{fn();count++;console.log('PASS '+name);};
const generator=()=>{const g=new EE.HP33120A();g.setLoad('50Ω');return g;};
const scope=()=>new EE.DigitalOscilloscope({getContext:()=>({})});
const fresh=()=>{const m=new EE.Simulation(new EE.Breadboard({getContext:()=>({})}).buses());m.load();return m;};
function menu(g){['shift','enter','right','right','right','down','down'].forEach(k=>g.key(k));}
test('Three-level High-Z ritual is pending until Enter; load changes preserve source voltage',()=>{
  const g=generator(),v=g.source().phasor(1).re;menu(g);assert.equal(g.display().text,'50 OHM');g.key('right');assert.equal(g.display().text,'HIGH Z');assert.equal(g.load,'50Ω');g.key('enter');assert.equal(g.load,'Hi-Z');near(g.source().phasor(1).re,v);near(g.vpp,10);
});
test('Menu off cancels a pending termination change and Up walks back through levels',()=>{const g=generator();menu(g);g.key('right');g.key('up');assert.equal(g.display().text,'1: OUT TERM');g.key('up');assert.equal(g.display().text,'D: SYS MENU');g.key('shift');g.key('enter');assert.equal(g.menu,null);assert.equal(g.load,'50Ω');});
test('Wrong displayed load causes a factor-of-two error at the same entered amplitude',()=>{const g=generator();g.set('vpp',4);const wrong=g.source().phasor(1).re;g.setLoad('Hi-Z');g.set('vpp',4);near(wrong/g.source().phasor(1).re,2);});
test('Digit navigation edits only the selected decade, with carry and limits',()=>{const g=generator();g.select('frequency');g.key('left');g.turn(1);near(g.frequency,310);g.key('right');g.key('right');g.turn(-1);near(g.frequency,309.9);g.set('frequency',.0001);g.digit=-4;g.turn(-1);near(g.frequency,.0001);});
test('Numeric entry commits kHz, mVrms, signed offset, backspace and cancellation',()=>{const g=generator();g.key('frequency');g.key('number');g.key('2');g.key('down');near(g.frequency,2000);g.key('vpp');g.key('number');'100'.split('').forEach(k=>g.key(k));g.key('shift');g.key('down');near(g.vpp,.1*2*Math.sqrt(2));g.key('offset');g.key('number');'-12'.split('').forEach(k=>g.key(k));g.key('left');g.key('enter');near(g.offset,-1);g.key('frequency');g.key('number');g.key('9');g.key('shift');g.key('number');near(g.frequency,2000);assert.equal(g.entry,null);});
test('Rejected entry preserves output state and lights ERROR',()=>{const g=generator();g.key('vpp');g.key('number');'999'.split('').forEach(k=>g.key(k));g.key('enter');near(g.vpp,5);near(g.offset,0);assert.ok(g.error);});
test('Square duty cycle includes DC and even harmonics in the nodal result',()=>{const m=fresh();m.parts=[];m.wires=[{a:'gen.out',b:'scope.ch1'}];m.generator.waveform='square';m.generator.vpp=2;m.generator.duty=25;m.compute();near(m.signals[0].offset,-.5,1e-4);assert.ok(m.signals[0].terms.some(t=>t.h===2&&Math.abs(t.re)>.1));});
test('Probe Comp is a separate 1 kHz 3 Vpp source with physical loading',()=>{const m=fresh();m.parts=[];m.wires=[{a:'scope.comp',b:'scope.ch1'}];m.generator.frequency=300;m.compute();const s=m.signals[0];near(s.frequency,1000);near(s.vpp,3,.04);near(s.offset,1.5,.001);m.termination[0]=50;m.compute();near(m.signals[0].vpp,s.vpp/2,.001);});
test('Independent 300 Hz generator and 1 kHz Probe Comp stay independent on two channels',()=>{const m=fresh();m.parts=[];m.wires=[{a:'gen.out',b:'scope.ch1'},{a:'scope.comp',b:'scope.ch2'}];m.compute();near(m.signals[0].frequency,300);near(m.signals[1].frequency,1000);const s=scope();s.acquire(m.signals);assert.equal(s.phaseDifference(),null);near(m.signals[1].sample(.001),m.signals[1].sample(0));});
test('Grounding Probe Comp collapses its signal and produces an earth-short event',()=>{const m=fresh();m.parts=[];m.wires=[{a:'scope.comp',b:'scope.ch1'},{a:'scope.comp',b:'scope.g1'}];m.compute();near(m.signals[0].vpp,0);assert.ok(m.failure.history.some(e=>e.key==='scope.g1'));});
test('Normal trigger holds the last frame; Single waits then captures exactly once',()=>{const m=fresh(),s=scope();s.acquire(m.signals);const old=s.signals;s.triggerMode='Normal';s.triggerLevel=100;m.generator.set('frequency',500);m.compute();s.acquire(m.signals);assert.equal(s.signals,old);assert.equal(s.status,'Wait');s.single=true;s.run=false;s.acquire(m.signals);assert.equal(s.status,'Armed');s.triggerLevel=0;s.acquire(m.signals);assert.equal(s.single,false);assert.equal(s.status,'Stop');near(s.signals[0].frequency,500);});
test('Trigger slope changes the crossing by half a period and source selection is honored',()=>{const m=fresh(),s=scope();s.acquire(m.signals);const rising=s.trigger();s.triggerSlope='Falling';near(Math.abs(s.trigger()-rising),1/600,1e-7);s.triggerSource=1;assert.notEqual(s.trigger(),rising);});
test('Cursor selector uses Entry/Select, then rotates X1 and X2 independently',()=>{const m=fresh(),s=scope();s.acquire(m.signals);s.openMenu('cursors');s.softkey(2);s.entryStep(1);s.selectEntry();assert.equal(s.cursorSelected,'X2');const old=s.cursor[0];s.entryStep(1);near(s.cursor[0],old);near(s.cursor[1],.602);near(s.cursorReading().phase,-360*300*s.cursorReading().dt);s.softkey(3);assert.equal(s.softkeys()[4][1],'-108.00°');s.softkey(3);assert.equal(s.softkeys()[4][1],'-1000.0 µs');});
test('Channel coupling, inversion, probe scaling and measurement clear affect readouts',()=>{const m=fresh(),s=scope();s.acquire(m.signals);s.active=0;s.softkey(2);assert.equal(s.measurementValue('Pk-Pk',0),'100.00 V');s.softkey(0);s.softkey(0);assert.equal(s.measurementValue('Pk-Pk',0),'--');s.openMenu('measure');s.softkey(5);assert.equal(s.measurements.length,0);});
test('Default Setup restores new firmware settings without changing the circuit',()=>{const m=fresh(),s=scope();s.acquire(m.signals);s.triggerLevel=100;s.cursorMode='Track Waveform';s.probe=[10,10];s.reset();near(s.triggerLevel,0);assert.equal(s.cursorMode,'Manual');assert.deepEqual(s.probe,[1,1]);near(m.signals[0].vpp,10);});
console.log(`\n${count} new instrument firmware checks passed.`);
