const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { pathToFileURL } = require('node:url');
const { chromium } = require(process.env.EE_PLAYWRIGHT_PATH || 'playwright');
(async () => {
 const browser = await chromium.launch({channel:'chrome',headless:true});
 try {
  const context = await browser.newContext({viewport:{width:1512,height:1100}});
  const page = await context.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message)); page.on('requestfailed',r=>errors.push(r.url()));
  const url=pathToFileURL(path.resolve(__dirname,'../index.html')).href;
  await page.goto(url); await page.waitForFunction(()=>EE.bench && EE.i18n);
  assert.equal(await page.locator('html').getAttribute('lang'),'th');
  assert.equal(await page.locator('#worksheet-open').innerText(),'เปิดใบงาน ↗');
  const before=await page.evaluate(()=>({w:JSON.stringify(EE.bench.model.wires),r:EE.bench.model.signals[1].vpp,mode:EE.bench.model.generator.load}));
  await setGenerator(page,'frequency','500');
  assert.match(await page.locator('#bench-hint').innerText(),/ลากจากแจ็ค/);
  await page.locator('#worksheet-open').click();
  await page.locator('[data-row="a0"] [data-field="peak"]').fill('1.234');
  await page.locator('#check-sheet').click(); assert.match(await page.locator('#grade-a0').innerText(),/กรอกค่า/);
  await page.locator('#worksheet-dialog [data-language-toggle]').click();
  assert.equal(await page.locator('html').getAttribute('lang'),'en');
  assert.equal(await page.locator('[data-row="a0"] [data-field="peak"]').inputValue(),'1.234');
  assert.match(await page.locator('#grade-a0').innerText(),/Enter all four/);
  await page.locator('[data-close="worksheet-dialog"]').click();
  assert.equal(await page.locator('#worksheet-open').innerText(),'Open worksheet ↗');
  assert.equal(await page.evaluate(()=>EE.bench.model.generator.frequency),500);
  assert.equal(await page.evaluate(()=>JSON.stringify(EE.bench.model.wires)),before.w);
  assert.equal(await page.evaluate(()=>EE.bench.model.generator.load),'Hi-Z');
  await page.reload(); await page.waitForFunction(()=>EE.bench);
  assert.equal(await page.locator('html').getAttribute('lang'),'en');
  await page.locator('.topbar [data-language-toggle]').click();
  await page.locator('.fault-section summary').click();
  await page.locator('[data-fault="fuse"]').click(); await page.locator('[data-output="0"]').click();
  assert.match(await page.locator('#event-log').innerText(),/ฟิวส์/);
  assert.equal(await page.locator('#dmm-reading').innerText(),'ฟิวส์ขาด · 0.000 A');
  await page.locator('.topbar [data-language-toggle]').click(); assert.match(await page.locator('#event-log').innerText(),/Fuse open/);
  assert.equal(await page.evaluate(()=>EE.bench.model.dmm.fuse),'blown');
  await page.locator('.topbar [data-language-toggle]').click();
  await page.locator('#reset-bench').click();
  await page.screenshot({path:path.resolve(__dirname,'../output/playwright/thai-desktop.png'),fullPage:true});
  for(let i=0;i<6;i++) await page.locator('.topbar [data-language-toggle]').click();
  assert.equal(await page.locator('html').getAttribute('lang'),'th'); assert.equal(await page.locator('#measure-1').innerText(),'10.00 V');
  await page.reload(); await page.waitForFunction(()=>EE.bench); assert.equal(await page.locator('html').getAttribute('lang'),'th');
  await page.setViewportSize({width:393,height:852});
  assert.ok(await page.locator('.topbar [data-language-toggle]').isVisible());
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('#worksheet-open').click(); await page.locator('#worksheet-dialog [data-language-toggle]').click();
  assert.equal(await page.locator('html').getAttribute('lang'),'en'); await page.locator('#worksheet-dialog [data-language-toggle]').click();
  await page.locator('[data-close="worksheet-dialog"]').click();
  await page.screenshot({path:path.resolve(__dirname,'../output/playwright/thai-mobile.png'),fullPage:true});
  const blocked=await browser.newContext(); await blocked.addInitScript(()=>{Object.defineProperty(Storage.prototype,'getItem',{value(){throw new Error('blocked');}});Object.defineProperty(Storage.prototype,'setItem',{value(){throw new Error('blocked');}});});
  const p=await blocked.newPage();await p.goto(url);await p.waitForFunction(()=>EE.bench);assert.equal(await p.locator('html').getAttribute('lang'),'th');await p.locator('.topbar [data-language-toggle]').click();assert.equal(await p.locator('html').getAttribute('lang'),'en');
  assert.deepEqual(errors,[]);
  console.log('PASS Thai default, English/Thai toggle, persisted preference, retained circuit and worksheet, dynamic faults and grades, repeated toggles, mobile layout, blocked storage, zero page/network errors.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
const {setGenerator,highZ}=require('./front-panel-helpers.cjs');
