/* Integration gameplay: real pointer/keyboard actions, actual solver gates, offline file load. */
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {pathToFileURL}=require('node:url');const {chromium}=require(process.env.EE_PLAYWRIGHT_PATH||'playwright');
(async()=>{
const browser=await chromium.launch({channel:'chrome',headless:true});const out=path.resolve(__dirname,'../output/play-game');fs.mkdirSync(out,{recursive:true});
const report={checks:[],errors:[],failedRequests:[],externalRequests:[]};let page;
try{
const context=await browser.newContext({viewport:{width:1600,height:1050}});page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.stack));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});page.on('requestfailed',r=>report.failedRequests.push(r.url()));page.on('request',r=>{if(/^https?:/.test(r.url()))report.externalRequests.push(r.url());});
const url=pathToFileURL(path.resolve(__dirname,'../index.html')).href;await page.goto(url);await page.waitForFunction(()=>EE.missions);await page.evaluate(()=>EE.i18n.setLanguage('en'));
const test=async(name,action)=>{await action();assert.deepEqual(report.errors,[]);report.checks.push(name);console.log('PASS '+name);};
const settle=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
const pin=id=>page.evaluate(id=>EE.bench.board.position(id),id);
const clickPin=async id=>{const p=await pin(id);await page.mouse.click(p.x,p.y);};
const dragTile=async(index,id,shot)=>{const tile=page.locator('[data-part="'+index+'"]');await tile.scrollIntoViewIfNeeded();const r=await tile.boundingBox(),p=await pin(id);await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(p.x,p.y,{steps:12});assert.ok(await page.locator('#drag-ghost').isVisible());if(shot)await page.screenshot({path:path.join(out,shot)});await page.mouse.up();await settle();};
const connect=async(a,id)=>{await page.locator('#patch-bay [data-terminal="'+a+'"]').click();await clickPin(id);};
const checkNext=async()=>{await page.locator('#mission-check').click();assert.ok(await page.evaluate(()=>EE.missions.passed),await page.locator('#mission-checks').innerText());await page.locator('#mission-next').click();};
const fillReadings=async()=>{const readings=await page.evaluate(()=>({peak:(EE.bench.scope.signals[1].vpp/2).toFixed(3),phase:EE.bench.scope.phaseDifference().toFixed(2)}));await page.locator('#mission-peak').fill(readings.peak);if(await page.locator('#mission-phase').isVisible())await page.locator('#mission-phase').fill(readings.phase);};
await test('Local patch bay clips leads to the work area and masks every control',async()=>{assert.ok(await page.locator('#wire-workspace-clip path').count());const result=await page.evaluate(()=>{const clip=document.querySelector('#wire-workspace-clip path');return{rule:clip.getAttribute('clip-rule'),cutouts:(clip.getAttribute('d').match(/M /g)||[]).length,buttons:document.querySelectorAll('#patch-bay button').length,overflow:document.documentElement.scrollWidth>innerWidth};});assert.equal(result.rule,'evenodd');assert.equal(result.cutouts,result.buttons+2);assert.equal(result.overflow,false);await page.screenshot({path:path.join(out,'clean-bench.png'),fullPage:true});});
await test('Mission starts empty with real validation; wrong step stays locked',async()=>{await page.locator('#mission-start').click();assert.equal(await page.evaluate(()=>EE.bench.model.parts.length),0);assert.equal(await page.evaluate(()=>EE.interaction.open),true);await page.locator('#mission-check').click();assert.equal(await page.evaluate(()=>EE.missions.passed),false);assert.equal(await page.locator('#mission-next').isVisible(),false);assert.equal(await page.evaluate(()=>EE.missions.step),0);await page.screenshot({path:path.join(out,'mission-workshop.png')});});
await test('Tray drag previews snapped leads, creates a real resistor, and supports both undo shortcuts',async()=>{await dragTile(0,'E12','drag-preview.png');assert.ok(await page.evaluate(()=>EE.bench.model.parts.some(p=>p.type==='R'&&p.a==='E12'&&p.b==='E29')));await page.keyboard.press('Control+z');assert.equal(await page.evaluate(()=>EE.bench.model.parts.length),0);await page.keyboard.press('Control+Shift+z');assert.equal(await page.evaluate(()=>EE.bench.model.parts.length),1);await page.keyboard.press('Meta+z');assert.equal(await page.evaluate(()=>EE.bench.model.parts.length),0);await page.keyboard.press('Meta+Shift+z');assert.equal(await page.evaluate(()=>EE.bench.model.parts.length),1);await checkNext();});
await test('Failed attempt restores only current checkpoint and preserves the earlier resistor step',async()=>{await dragTile(3,'D30');await page.locator('#mission-check').click();assert.equal(await page.evaluate(()=>EE.missions.passed),false);await page.locator('#mission-retry').click();assert.equal(await page.evaluate(()=>EE.missions.step),1);assert.equal(await page.evaluate(()=>EE.bench.model.parts.length),1);assert.equal(await page.evaluate(()=>EE.missions.completed.length),1);await dragTile(3,'D29');await checkNext();});
await test('Patch labels and pin clicks wire source and grounded probes into the actual netlist',async()=>{await connect('gen.out','A12');await connect('gen.gnd','A49');await checkNext();for(const pair of [['scope.ch1','B12'],['scope.ch2','B29'],['scope.g1','B49'],['scope.g2','C49']])await connect(...pair);assert.equal(await page.evaluate(()=>EE.bench.model.wires.length),6);await checkNext();await page.screenshot({path:path.join(out,'mission-wired.png')});});
await test('Each 3D instrument opens its own live panel and source settings produce the expected RC response',async()=>{await page.locator('#mission-focus').click();assert.equal(await page.locator('#scene-dock .instrument').count(),1);assert.ok(await page.locator('#scene-dock #generator').isVisible());await highZ(page);await setGenerator(page,'frequency','300');await setGenerator(page,'vpp','10.5');await page.locator('#gen-output').click();const signal=await page.evaluate(()=>EE.bench.model.signals.map(s=>s.vpp));assert.ok(signal[0]>9.9&&signal[0]<10.1);assert.ok(signal[1]>2.3&&signal[1]<2.4);await checkNext();await page.locator('#mission-focus').click();assert.equal(await page.locator('#scene-dock .instrument').count(),1);await page.locator('#scope-auto').click();await checkNext();await page.screenshot({path:path.join(out,'mission-scope.png')});});
await test('Measurement gate rejects guesses, accepts actual readings, and advances through all capacitances',async()=>{await page.locator('#mission-peak').fill('50');await page.locator('#mission-phase').fill('0');await page.locator('#mission-check').click();assert.equal(await page.evaluate(()=>EE.missions.passed),false);await fillReadings();await checkNext();for(const c of ['0.000001','0.0000001']){await page.locator('#mission-focus').click();await page.locator('#preset-cap').selectOption(c);await fillReadings();await checkNext();}assert.ok(await page.locator('#mission-map').isVisible());assert.equal(await page.evaluate(()=>EE.missions.unlocked),1);assert.equal(await page.evaluate(()=>EE.missions.records.length),3);});
await test('Frequency chapter unlocks only after success and grades all six real measurements',async()=>{assert.equal(await page.locator('.chapter-card').nth(2).isDisabled(),true);await page.locator('.chapter-card').nth(1).click();for(const f of [50,200,500,1000,2000,5000]){await setGenerator(page,'frequency',String(f));await fillReadings();await checkNext();}assert.equal(await page.evaluate(()=>EE.missions.records.length),9);assert.equal(await page.evaluate(()=>EE.missions.unlocked),2);});
await test('Series chapter uses removable and draggable capacitors with real equivalent capacitance',async()=>{await page.locator('.chapter-card').nth(2).click();const point=await page.evaluate(()=>{const part=EE.bench.model.parts.find(p=>p.type==='C'),a=EE.bench.board.position(part.a),b=EE.bench.board.position(part.b);return{x:(a.x+b.x)/2,y:(a.y+b.y)/2-22*EE.bench.board.metrics().scale};});await page.mouse.click(point.x,point.y);await page.locator('#part-delete').click();assert.equal(await page.evaluate(()=>EE.bench.model.parts.length),1);await dragTile(2,'D29');await dragTile(3,'E39');assert.ok(await page.evaluate(()=>Math.abs(EE.bench.model.equivalentCapacitance()/.6875e-6-1)<1e-6));await checkNext();await page.locator('#mission-focus').click();await setGenerator(page,'vpp','10.5');await page.locator('#gen-output').click();await fillReadings();await checkNext();});
await test('Photo 10 fault cannot pass until CH2 is actually rewired; all 18 steps complete',async()=>{assert.ok(await page.evaluate(()=>EE.bench.model.anomaly));await page.locator('#mission-focus').click();await fillReadings();await page.locator('#mission-check').click();assert.equal(await page.evaluate(()=>EE.missions.passed),false);await page.locator('.connection-editor summary').click();const index=await page.evaluate(()=>EE.bench.model.wires.findIndex(w=>w.a==='scope.ch2'||w.b==='scope.ch2'));await page.locator('.wire-entry').nth(index).getByRole('button',{name:'Unplug',exact:true}).click();await page.locator('#patch-bay [data-terminal="scope.ch2"]').scrollIntoViewIfNeeded();await connect('scope.ch2','A29');assert.ok(!await page.evaluate(()=>EE.bench.model.anomaly));await fillReadings();await page.screenshot({path:path.join(out,'series-corrected.png')});await checkNext();assert.equal(await page.evaluate(()=>EE.missions.unlocked),3);assert.equal(await page.evaluate(()=>EE.missions.completed.length),18);assert.equal(await page.evaluate(()=>EE.missions.records.length),11);const downloadPromise=page.waitForEvent('download');await page.locator('#mission-export').click();const download=await downloadPromise,file=path.join(out,'mission-report.json');await download.saveAs(file);const report=JSON.parse(fs.readFileSync(file));assert.equal(report.records.length,11);assert.equal(report.completedSteps.length,18);assert.equal(report.measurementUnits.peak,'V');});
await test('Mission resumes working circuit and checkpoint after reload without awarding duplicate completion',async()=>{await page.reload();await page.waitForFunction(()=>EE.missions);await page.locator('#mission-menu').click();await page.locator('#mission-continue').click();assert.equal(await page.evaluate(()=>EE.missions.chapter),2);assert.equal(await page.evaluate(()=>EE.missions.step),2);assert.equal(await page.evaluate(()=>EE.missions.completed.length),18);assert.equal(await page.evaluate(()=>EE.missions.passed),false);assert.ok(!await page.evaluate(()=>EE.bench.model.anomaly));await page.locator('#mission-menu').click();await page.locator('#mission-pause').click();await page.locator('#assembly-close').click();});
await test('Tabletop board drag moves geometry and wires, preserves electrical readings and is undoable',async()=>{await page.locator('#scene-arrange').click();await settle();const point=await page.evaluate(()=>EE.scene.renderer.project([0,.858,.4]));const voltage=await page.evaluate(()=>EE.bench.model.signals[1].vpp);await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+110,point.y+30,{steps:10});await page.mouse.up();assert.ok(await page.evaluate(()=>Math.abs(EE.scene.boardOffset[0])>.1));assert.equal(await page.evaluate(()=>EE.bench.model.signals[1].vpp),voltage);await page.keyboard.press('Control+z');assert.deepEqual(await page.evaluate(()=>EE.scene.boardOffset),[0,0]);await page.keyboard.press('Control+Shift+z');assert.ok(await page.evaluate(()=>Math.abs(EE.scene.boardOffset[0])>.1));await page.keyboard.press('Escape');await page.screenshot({path:path.join(out,'scene-arranged.png')});});
await test('Component bodies drag to new holes; movement and deletion restore with undo',async()=>{await page.keyboard.press('b');await page.evaluate(()=>{EE.bench.model.generator.enabled=false;EE.bench.update();});const old=await page.evaluate(()=>{const p=EE.bench.model.parts.find(p=>p.type==='C');return{id:p.id,a:p.a,b:p.b};});const point=await page.evaluate(id=>{const p=EE.bench.model.parts.find(p=>p.id===id),a=EE.bench.board.position(p.a),b=EE.bench.board.position(p.b);return{x:(a.x+b.x)/2,y:(a.y+b.y)/2-22*EE.bench.board.metrics().scale};},old.id);const target=await pin('G10');await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(target.x,target.y,{steps:10});await page.mouse.up();assert.equal(await page.evaluate(id=>EE.bench.model.parts.find(p=>p.id===id).a,old.id),'G10');await page.keyboard.press('Control+z');assert.equal(await page.evaluate(id=>EE.bench.model.parts.find(p=>p.id===id).a,old.id),old.a);await page.evaluate(id=>EE.interaction.select(id),old.id);await page.keyboard.press('Delete');assert.ok(!await page.evaluate(id=>EE.bench.model.parts.some(p=>p.id===id),old.id));await page.keyboard.press('Control+z');assert.ok(await page.evaluate(id=>EE.bench.model.parts.some(p=>p.id===id),old.id));await page.locator('#assembly-close').click();});
await test('Direct mesh power and knob controls affect generator and group each drag into one undo command',async()=>{await page.evaluate(()=>{EE.bench.model.generator.select('frequency');EE.scene.pose(EE.scene.homePose);EE.interaction.clearSelection();});await settle();const p=await page.evaluate(()=>{const i=EE.scene.instruments.find(i=>i.name==='generator'),p=i.center,s=i.size;return{power:EE.scene.renderer.project([p[0]-s[0]*.4,p[1]-s[1]*.31,p[2]+s[2]/2+.026]),knob:EE.scene.renderer.project([p[0]+s[0]*.36,p[1]+.018,p[2]+s[2]/2+.04])};});const enabled=await page.evaluate(()=>EE.bench.model.generator.enabled);await page.mouse.click(p.power.x,p.power.y);assert.equal(await page.evaluate(()=>EE.bench.model.generator.enabled),!enabled);const f=await page.evaluate(()=>EE.bench.model.generator.frequency),n=await page.evaluate(()=>EE.history.past.length);await page.mouse.move(p.knob.x,p.knob.y);await page.mouse.down();await page.mouse.move(p.knob.x,p.knob.y-45,{steps:8});await page.mouse.up();assert.ok(await page.evaluate(()=>EE.bench.model.generator.frequency)>f);assert.equal(await page.evaluate(()=>EE.history.past.length),n+1);await page.keyboard.press('Control+z');assert.equal(await page.evaluate(()=>EE.bench.model.generator.frequency),f);});
await test('Damage, repair state and activity history are included in undo; log exports valid JSON',async()=>{await page.evaluate(()=>{EE.bench.model.fault('resistor');EE.bench.update();});await page.keyboard.press('1');await page.locator('[data-output="0"]').click();assert.equal(await page.evaluate(()=>EE.bench.model.parts[0].state),'burnt');await page.locator('#command-undo').click();assert.equal(await page.evaluate(()=>EE.bench.model.parts[0].state),'good');assert.equal(await page.evaluate(()=>EE.bench.model.psu.channels[0].enabled),false);await page.locator('#command-log').click();assert.ok(await page.locator('#activity-list li').count()>10);const downloadPromise=page.waitForEvent('download');await page.locator('#activity-export').click();const download=await downloadPromise;const file=path.join(out,'session-log.json');await download.saveAs(file);assert.ok(JSON.parse(fs.readFileSync(file)).actions.length>10);await page.locator('#activity-close').click();});
await test('Language changes retain campaign, history and circuit state; keyboard shortcuts do not steal text editing',async()=>{const before=await page.evaluate(()=>JSON.stringify({m:EE.history.snapshot(),past:EE.history.past.length,c:EE.missions.completed}));await page.locator('.topbar [data-language-toggle]').click();assert.equal(await page.locator('#command-log').innerText(),'ประวัติ');assert.equal(await page.evaluate(()=>JSON.stringify({m:EE.history.snapshot(),past:EE.history.past.length,c:EE.missions.completed})),before);await page.keyboard.press('3');await page.locator('#gen-number').click();await page.keyboard.press('b');assert.equal(await page.evaluate(()=>EE.interaction.open),false);});
const mobile=await browser.newContext({viewport:{width:393,height:852},deviceScaleFactor:2,isMobile:true,hasTouch:true});const p=await mobile.newPage();p.on('pageerror',e=>report.errors.push(e.stack));await p.goto(url);
await test('Mobile mission and assembly remain usable without horizontal overflow',async()=>{await p.locator('#mission-start').tap();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await p.locator('#mission-check').isVisible());await p.locator('[data-part="0"]').tap();await p.locator('.connection-editor summary').tap();await p.locator('#wire-from').fill('E12');await p.locator('#wire-to').fill('E29');await p.locator('#connect-wire').tap();assert.equal(await p.evaluate(()=>EE.bench.model.parts.length),1);await p.locator('#mission-check').tap();assert.ok(await p.evaluate(()=>EE.missions.passed));await p.locator('#mission-panel').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'mobile-workshop.png')});await p.locator('#assembly-close').tap();assert.ok(await p.locator('#scene-canvas').isVisible());});await mobile.close();
report.finalState=JSON.parse(await page.evaluate(()=>render_game_to_text()));assert.deepEqual(report.errors,[]);assert.deepEqual(report.failedRequests,[]);assert.deepEqual(report.externalRequests,[]);
fs.writeFileSync(path.join(out,'game-verification.json'),JSON.stringify(report,null,2));console.log(report.checks.length+' gameplay checks passed; console and network clean.');
}catch(e){if(page){await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});report.state=await page.evaluate(()=>window.render_game_to_text?.()).catch(()=>null);}fs.writeFileSync(path.join(out,'game-failure.json'),JSON.stringify({...report,error:e.stack},null,2));throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
const {setGenerator,highZ}=require('./front-panel-helpers.cjs');
